<?php

namespace Deb\TopicsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends DocumentRepository
{        
    public function isUserAnyTopicMember($user_id, $except_topic_id = null){
        $qb = $this->createQueryBuilder('Topic');
        $TopicsFound = $qb
                ->field('members')->equals($user_id)
                ->addOr($qb->expr()->field('status_code')->equals('waiting'))
                ->addOr($qb->expr()->field('status_code')->equals('processing'));
        if($except_topic_id){
            $TopicsFound->field('id')->notEqual($except_topic_id);            
        }        
                
                
        $TopicsFound = $TopicsFound->getQuery()->execute()->count();
        //Если не состоит в обсуждения то, возвращаем false
        return ($TopicsFound > 0) ? true : false;
                        
    }
    
}