topics_list:
    path:     /
    defaults: { _controller: DebTopicsBundle:TopicsList:index }
        
topic_detail:
    path:     /detail
    defaults: { _controller: DebTopicsBundle:TopicDetail:index }    
    
info_page:
    path:     /info
    defaults: { _controller: DebTopicsBundle:InfoPage:index }   
    
personal_section:
    path:     /personal
    defaults: { _controller: DebTopicsBundle:PersonalSection:index }   